# -*- coding: utf-8 -*-
"""Hachathon-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r1nI33kuTq44YhRegrTUaJxd061ZnAHo

# if statements
"""

#increment the value by 1

num=2
if num>0:
    num=num+1
print("updated value:",num)

#Determine weather a person is eligible to vote by using  input

age=int(input("enter age of the person"))
if age>=18:
    print("The person is eligible to vote")

"""# if-else statements"""

#Determine weather a person is eligible to vote by using input

age=int(input("enter age of the person"))
if age>=18:
    print("The person is eligible to vote")
else:
    print("The person is not eligible to vote")

#find the number is even or odd by using input

numb=int(input("enter number:"))
if numb%2==0:
    print("even number")
else:
    print("odd number")

A company decides to give bonus to all its employees on New year. A 10% bonus on salary for all the male workers and
25% to females. build a programme to enter Salary and Gender(m or F) of employee.

salary=int(input("Enter the salary: "))
gender=input("Enter the gender (M or F): ").upper()
if gender=='M':
    bonus=(salary*10)/100
    print("bonus amount for male",bonus)
else:
    bonus=(salary*25)/100
    print("bonus amount for male",bonus)

"""# if -elif- else Statement"""

# check weather the number is positive or negitive or equal to zero using input

number=int(input("enter number:"))
if number>0:
    print("positive number")
elif number<0:
    print("negative number")
else:
    print("equals to zero")

# Test Weather the charcter is vowel or not vowel using input

character=input("enter a character:")
if character in "aeiou":
    print("vowels")
elif character in  "b, c, d, f, g, h, j, k, l, m, n, p, q, r, s, t, v, w, x, y, z":
    print("consonants")
else:
    print("special characters or numbers")

#Given an integer input perform the following conditional actions:

#If n is odd, print odd
#If n is even and in the inclusive range of 2 to 5, print small
#If n is even and in the inclusive range of 6 to 20, print medium
#If n is even and greater than 20, print big

a=int(input("enter number:"))
if a%2!=0:
    print("odd")
elif a%2==0 and 2 <= a <= 5:
    print("small")
elif a%2==0 and 6 <= a <= 20:
    print("medium")
else:
    print("big")

"""# while loop"""

# print first 10 numbers

i=1
while i<=10:
    print(i)
    i=i+1

# find average and sum for first 10 numbers

i=1
sum=0
count=0
while i <=10:
    sum+= i
    count+=1
    i+=1
average = sum / count
print("Sum of the first 10 numbers:", sum)
print("Average of the first 10 numbers:", average)

#Draw a line using while loop

i=1
while i<=10:
    print("|")
    i+=1

#calculate the sum of m to n  numbers using input

m=int(input("enter m number:"))
n=int(input("enter n number"))
sum=0
while m<=n:
    sum=sum+m
    m+=1
print("sum of  numbers from m to n are",sum)

# countdown 10 to 0 using input

i=10
while i>=1:
    print(i)
    i-=1

"""# for loop"""

#Multiplication table using input

number=int(input("enter number"))
for i in range(1,11):
    result=number*i
    print(f"{number}x{i}={result}")

#print even and odd for range of number

n=int(input("enter number"))
for i in range(2,n,2):
    print("even number",i)
for j in range(1,n,2):
    print("odd number",j)

# break statement

for i in  range(1,11):
    if i==6:
        break
    print(i,end=" ")

#continue statement

for i in  range(1,11):
    if i==8:
        continue
    print(i,end=" ")

# all leap years from 1800 - 2021

print("all leap years from 1800 - 2021")
for i in range(1800,202,4):
    print(i)

"""# User defined function"""

#creating arethematic operators using user defined functions

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Cannot divide by zero!"
    return a / b

def modulo(a, b):
    if b == 0:
        return "Cannot divide by zero!"
    return a % b

# Example usage
num1 = 10
num2 = 5

print("Addition:", add(num1, num2))
print("Subtraction:", subtract(num1, num2))
print("Multiplication:", multiply(num1, num2))
print("Division:", divide(num1, num2))
print("Modulo:", modulo(num1, num2))

#Welcome With input

def fun():
    name=input("enter name:")
    print(f"Welcome,{name}")
fun()

"""# Lambda function"""

# sum using lambda function

n=lambda a,b:a+b
print(n(100,200))

# create a list using loop

list1=[]
for i in range(1,11):
    list1.append(i)
print(list1)

# Create a list of first 10 number using list comprehension

list2=[i for i in range(1, 11)]
print(list2)

# select all the even number form the list with filter()

num=[1,2,3,4,5,6,7,8,9,10]
n=list(filter(lambda a:a%2==0,num))
print(n)

# get  the squares of numbers form the list with map()

list1=[4,5,6]
squares=list(map(lambda n:n**2,list1))
print(squares)

#get the sum of numbers of the list using reduce()

from functools import reduce
list1=[1,2,3,4,5,6,7,8,9,10]
sum=(reduce(lambda x,y:x+y,list1))
print(sum)